version: '3.8'

services:
  nats:
    image: "nats:latest"
    ports:
      - "4222:4222"  # 클라이언트 연결
      - "8222:8222"  # HTTP 모니터링
      - "6222:6222"  # 클러스터링
    volumes:
      - ./nats-data:/data
      
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

